### ISSUE TITLE
Cannot find OpenJDK 11 in fresh environment

### ISSUE THREAD

**Issue by atk91** [scalameta/metals-languageclient#4]
**Describe the bug**

Cannot use metals with openjdk11 when editing .scala file

**To Reproduce** 

1. Install openjdk11
2. `nvim main.scala` when `main.scala` is absent

**Expected behavior**

Metals should work

**Actual behaviour**

Error message fires: 
`Unable to find a Java 8 or Java 11 installation on this computer. To fix this problem, update the 'Java Home' setting
 to point to a Java 8 or Java 11 home directory:`

Metals does not work

**Installation:**

- Operating system: Linux
- Vim or nvim version: NVIM v0.4.3
- coc-metals extension version: 0.5.3
- Metals version: 0.8.0

**Search terms**
java not found, openjdk 11

**Comment by ckipp01** [comment]
Since the code that is doing this is now located in here, I've moved this issue into here.

I've been able to reproduce this consistently both in the docker environment that @atk91 has provided, and in a fresh vm locally. If you go to a fresh environment that has OpenJDK 11 installed and use the below script with the semver range that we are using, it won't pick up the jdk.

```javascript
const LocateJavaHome = require('locate-java-home').default                                                     

LocateJavaHome({ version: ">=1.8 <=1.11" }, function(error, javaHomes) {                                     
   javaHomes.forEach(function(homeInfo) {                                                                      
      console.log("Found Java " + homeInfo.version + " at " + homeInfo.path);                                  
      if (homeInfo.isJDK) {                                                                                    
        console.log("It's a JDK!");                                                                            
      } else {
    console.log("It's something else")
      }                                                                                                        
   });                                                                                                         
});
```
I don't believe we've caught this because I'm assuming the majority of users have `$JAVA_HOME` set which is picked up and used. For example, that's what happens in my local environment when I launch Metals. The script for me returns an empty array, but the java version that my `$JAVA_HOME` specifies is still picked up and used.

If I change the part of the line with the versions in the script above to what I have below, then OpenJDK does indeed seem to be picked up. As @atk91 mentioned in Gitter, it seems to be that the way the version is being detected has changed somehow between 8 and 11.

```javascript
{ version: ">=1.8 <=11" }
```
Again the above does correctly pick up the OpenJDK 11, but correctly won't pick up 12.

Thoughts on changing this @gabro?

**Comment by gabro** [comment]
Ok, apparently Java versions go like 1.8, 1.9, 1.10, 10, 11, 12, 13, so I believe the fix makes sense 👍 Thanks for reporting @atk91, very helpful reproduction too!

**Comment by ckipp01** [comment]
Awesome. Thanks @gabro! 👍

**Comment by gabro** [comment]
I’ll release tomorrow so that this can be fixed on the clients!
